# Generated by Django 5.2.5 on 2025-08-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=55)),
                ('designation', models.CharField(max_length=60)),
                ('department', models.CharField(max_length=70)),
                ('qualification', models.CharField(max_length=65)),
            ],
        ),
    ]
